[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
#libs = ['lib']
test = 'test'
cache_path  = 'cache_forge'
evm_version = "shanghai"
solc = "0.8.24"
optimizer_runs = 200


[rpc_endpoints]
bsc-test = "${BSC_TESTNET_RPC_URL}"
bsc = "${BSC_RPC_URL}"

[etherscan]
bsc-test = { key = "${BSCSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}" }
